// Bunny.net Stream URL builders
// No SDK dependency — pure URL construction from video GUIDs
// Docs: https://docs.bunny.net/docs/stream-embedding-videos

// Configure these once after creating your Bunny.net Stream library
const PULL_ZONE = "vz-4fcbca30-3f7"
const CDN_HOSTNAME = `${PULL_ZONE}.b-cdn.net`

/**
 * Update the pull zone after setting up Bunny.net Stream.
 * The pull zone is shown in Stream > Library > API > Pull Zone URL
 */
export function configureBunny(pullZone: string) {
  // This is a runtime override — for development/testing
  ;(globalThis as any).__bunnyPullZone = pullZone
}

function getHostname(): string {
  return (globalThis as any).__bunnyPullZone
    ? `${(globalThis as any).__bunnyPullZone}.b-cdn.net`
    : CDN_HOSTNAME
}

/**
 * Normalize a video reference to a bare GUID.
 * Editor-added projects sometimes store a full player URL
 * (e.g. https://player.mediadelivery.net/play/633708/<guid>) instead of the
 * GUID — extract it so thumbnail/preview/play URLs are never malformed.
 */
export function normalizeVideoId(videoId: string): string {
  const m = videoId.match(
    /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i
  )
  return m ? m[0] : videoId
}

/** Static thumbnail image extracted from the video */
export function thumbnailUrl(videoId: string): string {
  return `https://${getHostname()}/${normalizeVideoId(videoId)}/thumbnail.jpg`
}

/** Animated WebP preview — auto-generated by Bunny, small file size */
export function previewUrl(videoId: string): string {
  return `https://${getHostname()}/${normalizeVideoId(videoId)}/preview.webp`
}

/** Direct MP4 at a specific quality level */
export function videoUrl(
  videoId: string,
  quality: "360p" | "480p" | "720p" | "1080p" = "720p"
): string {
  return `https://${getHostname()}/${normalizeVideoId(videoId)}/play_${quality}.mp4`
}

/** HLS adaptive streaming playlist — best quality, auto-adjusts to connection */
export function hlsUrl(videoId: string): string {
  return `https://${getHostname()}/${normalizeVideoId(videoId)}/playlist.m3u8`
}

/** Bunny.net embed iframe URL (fallback if needed) */
export function embedUrl(videoId: string): string {
  return `https://iframe.mediadelivery.net/embed/${normalizeVideoId(videoId)}`
}
